export enum IpcChannels {
  CONFIG_GET = 'CONFIG_GET',
  CONFIG_SET = 'CONFIG_SET',

  CREDENTIALS_GET = 'CREDENTIALS_GET',
  CREDENTIALS_SET = 'CREDENTIALS_SET',

  LIFX_CALL_API = 'LIFX_CALL_API',

  TWITCH_AUTH_CLEAR = 'TWITCH_AUTH_CLEAR',
  TWITCH_AUTH_START = 'TWITCH_AUTH_START',
  TWITCH_PUBSUB_START = 'TWITCH_PUBSUB_START',
  TWITCH_PUBSUB_STOP = 'TWITCH_PUBSUB_STOP',
  TWITCH_PUBSUB_EVENT = 'TWITCH_PUBSUB_EVENT',
}
