export enum IPCEvents {
  CREDENTIALS_GET = 'CREDENTIALS_GET',
  CREDENTIALS_SET = 'CREDENTIALS_SET',

  LIFX_CALL_API = 'LIFX_CALL_API',

  TWITCH_AUTH_CLEAR = 'TWITCH_AUTH_CLEAR',
  TWITCH_AUTH_START = 'TWITCH_AUTH_START',
  TWITCH_PUBSUB_START = 'TWITCH_PUBSUB_START',
  TWITCH_PUBSUB_STOP = 'TWITCH_PUBSUB_STOP',
  TWITCH_PUBSUB_EVENT = 'TWITCH_PUBSUB_EVENT',

  CONFIG_GET_LIFX_STATES = 'CONFIG_GET_LIFX_STATES',
  CONFIG_GET_LIFX_STATE = 'CONFIG_GET_LIFX_STATE',
  CONFIG_SET_LIFX_STATE = 'CONFIG_SET_LIFX_STATE',
  CONFIG_DELETE_LIFX_STATE = 'CONFIG_DELETE_LIFX_STATE',
}
