export enum IPCEvents {
  GET_CREDENTIAL = 'GET_CREDENTIAL',
  SET_CREDENTIAL = 'SET_CREDENTIAL',
  TWITCH_AUTH_CLEAR = 'TWITCH_AUTH_CLEAR',
  TWITCH_AUTH_START = 'TWITCH_AUTH_START',
  LIFX_CALL_API = 'LIFX_CALL_API',
  TWITCH_PUBSUB_START = 'TWITCH_PUBSUB_START',
  TWITCH_PUBSUB_STOP = 'TWITCH_PUBSUB_STOP',
  TWITCH_PUBSUB_EVENT = 'TWITCH_PUBSUB_EVENT',
}
